/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    SealedBidFeedlot: {
      address:
        "0x2ed90212a4de48dba638da4250ed7dcb3c922dd8c3aff6f867771db69dfa037",
      abi: [
        {
          type: "impl",
          name: "SealedBidFeedlotImpl",
          interface_name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::internal::bounded_int::BoundedInt::<0, 30>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::SealedBidFeedlot::LotInfo",
          members: [
            {
              name: "productor",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "raza",
              type: "core::felt252",
            },
            {
              name: "peso_inicial",
              type: "core::integer::u256",
            },
            {
              name: "cantidad_animales",
              type: "core::integer::u256",
            },
            {
              name: "metadata_uri",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "start_time",
              type: "core::integer::u64",
            },
            {
              name: "duration",
              type: "core::integer::u64",
            },
            {
              name: "finalizado",
              type: "core::bool",
            },
            {
              name: "mejor_puja",
              type: "core::integer::u256",
            },
            {
              name: "mejor_postor",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
          items: [
            {
              type: "function",
              name: "create_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "productor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "raza",
                  type: "core::felt252",
                },
                {
                  name: "peso_inicial",
                  type: "core::integer::u256",
                },
                {
                  name: "cantidad_animales",
                  type: "core::integer::u256",
                },
                {
                  name: "metadata_uri",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "duration",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "commit_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reveal_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nonce",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "finalize_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_winning_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_info",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::SealedBidFeedlot::LotInfo",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_count",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_auction_verifier",
              inputs: [
                {
                  name: "verifier_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "finalize_with_zk",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "winner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "winner_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "proof",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_bidders_count",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_bidder_at",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "index",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_payment_verifier",
              inputs: [
                {
                  name: "verifier_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "verify_payment",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "proof",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_payment_done",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_winner",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "(core::starknet::contract_address::ContractAddress, core::integer::u256)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "debug_reveal",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nonce",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "(core::felt252, core::felt252, core::starknet::contract_address::ContractAddress, core::starknet::contract_address::ContractAddress)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_revealed_bids",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::starknet::contract_address::ContractAddress, core::integer::u256, core::felt252)>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::AuctionFinalized",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "winner_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::PaymentVerified",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::WinnerRecorded",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::Event",
          kind: "enum",
          variants: [
            {
              name: "AuctionFinalized",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::AuctionFinalized",
              kind: "nested",
            },
            {
              name: "PaymentVerified",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::PaymentVerified",
              kind: "nested",
            },
            {
              name: "WinnerRecorded",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::WinnerRecorded",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2d66239dd1e281b8630ae044b4e4868d68403b55817ca9e1136b3241cb87397",
    },
  },
  sepolia: {
    SealedBidFeedlot: {
      address:
        "0x2eecc60f54fc87be7db63e19f0291b43ce403258ba674bf6bc221601376194",
      abi: [
        {
          type: "impl",
          name: "SealedBidFeedlotImpl",
          interface_name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::internal::bounded_int::BoundedInt::<0, 30>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::SealedBidFeedlot::LotInfo",
          members: [
            {
              name: "productor",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "raza",
              type: "core::felt252",
            },
            {
              name: "peso_inicial",
              type: "core::integer::u256",
            },
            {
              name: "cantidad_animales",
              type: "core::integer::u256",
            },
            {
              name: "metadata_uri",
              type: "core::byte_array::ByteArray",
            },
            {
              name: "start_time",
              type: "core::integer::u64",
            },
            {
              name: "duration",
              type: "core::integer::u64",
            },
            {
              name: "finalizado",
              type: "core::bool",
            },
            {
              name: "mejor_puja",
              type: "core::integer::u256",
            },
            {
              name: "mejor_postor",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::SealedBidFeedlot::ISealedBidFeedlot",
          items: [
            {
              type: "function",
              name: "create_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "productor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "raza",
                  type: "core::felt252",
                },
                {
                  name: "peso_inicial",
                  type: "core::integer::u256",
                },
                {
                  name: "cantidad_animales",
                  type: "core::integer::u256",
                },
                {
                  name: "metadata_uri",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "duration",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "commit_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "commitment",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "reveal_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nonce",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "finalize_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_winning_bid",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_info",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::SealedBidFeedlot::LotInfo",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_count",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_auction_verifier",
              inputs: [
                {
                  name: "verifier_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "finalize_with_zk",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "winner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "winner_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "proof",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_bidders_count",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_bidder_at",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "index",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_payment_verifier",
              inputs: [
                {
                  name: "verifier_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "verify_payment",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "proof",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_payment_done",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_winner",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "(core::starknet::contract_address::ContractAddress, core::integer::u256)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "debug_reveal",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "nonce",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "(core::felt252, core::felt252, core::starknet::contract_address::ContractAddress, core::starknet::contract_address::ContractAddress)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_revealed_bids",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::starknet::contract_address::ContractAddress, core::integer::u256, core::felt252)>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::AuctionFinalized",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "winner_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::PaymentVerified",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::WinnerRecorded",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::SealedBidFeedlot::SealedBidFeedlot::Event",
          kind: "enum",
          variants: [
            {
              name: "AuctionFinalized",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::AuctionFinalized",
              kind: "nested",
            },
            {
              name: "PaymentVerified",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::PaymentVerified",
              kind: "nested",
            },
            {
              name: "WinnerRecorded",
              type: "contracts::SealedBidFeedlot::SealedBidFeedlot::WinnerRecorded",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x60d7092e8b2b4d111d757093f4d6dcc7b3cc329b60199f6fa6a3e33a1cc7071",
    },
  },
} as const;

export default deployedContracts;
